# SAHARA | NLP Utils - nlp_utils.py

CATEGORY_MAP = {
    "Fungal infection": "Skin & Fungal",
    "Allergy": "Allergy & Immune",
    "GERD": "Digestive",
    "Chronic cholestasis": "Digestive",
    "Drug Reaction": "Allergy & Immune",
    "Peptic ulcer diseae": "Digestive",
    "AIDS": "Infectious",
    "Diabetes": "Metabolic",
    "Gastroenteritis": "Digestive",
    "Bronchial Asthma": "Respiratory",
    "Hypertension": "Cardiovascular",
    "Migraine": "Neurological",
    "Cervical spondylosis": "Musculoskeletal",
    "Paralysis (brain hemorrhage)": "Neurological",
    "Jaundice": "Digestive",
    "Malaria": "Infectious",
    "Chicken pox": "Infectious",
    "Dengue": "Infectious",
    "Typhoid": "Infectious",
    "hepatitis A": "Infectious",
    "Hepatitis B": "Infectious",
    "Hepatitis C": "Infectious",
    "Hepatitis D": "Infectious",
    "Hepatitis E": "Infectious",
    "Alcoholic hepatitis": "Digestive",
    "Tuberculosis": "Respiratory",
    "Common Cold": "Respiratory",
    "Pneumonia": "Respiratory",
    "Dimorphic hemmorhoids(piles)": "Digestive",
    "Heart attack": "Cardiovascular",
    "Varicose veins": "Cardiovascular",
    "Hypothyroidism": "Metabolic",
    "Hyperthyroidism": "Metabolic",
    "Hypoglycemia": "Metabolic",
    "Osteoarthristis": "Musculoskeletal",
    "Arthritis": "Musculoskeletal",
    "(vertigo) Paroymsal  Positional Vertigo": "Neurological",
    "Acne": "Skin & Fungal",
    "Urinary tract infection": "Urological",
    "Psoriasis": "Skin & Fungal",
    "Impetigo": "Skin & Fungal",
}

def get_disease_category(disease: str) -> str:
    return CATEGORY_MAP.get(disease, "General Health")
